name: Petopia Market # Name of the workflow

on: # Define when the workflow should be triggered
  push: # Trigger the workflow on push events to the specified branches
    branches:
      - main
      - dev
  pull_request: # Trigger the workflow on pull requests targeting the specified branches
    branches:
      - dev
  pull_request_target: # Trigger the workflow on pull request targeting events for the specified branches
    branches:
      - dev
    types: [opened, reopened] # Trigger on pull request opened or reopened events

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest # Define the operating system for the job
    strategy:
      matrix: # Define a matrix for running tests with different configurations
        node-version: [20.x] # Define Node.js versions to test with
        mongodb-version: ["6.0"] # Define MongoDB versions to test with

    steps:
      - name: Checkout code # Step to checkout the repository code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }} # Step to set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB # Step to start MongoDB service
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: test-rs
          mongodb-port: 27017

      - name: Install backend dependencies # Step to install backend dependencies
        run: |
          cd Backend
          npm install

      - name: Run backend tests # Step to run backend tests
        env:
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
          ACCESS_TOKEN_EXPIRY: 2d # Expiry time for access token
          REFRESH_TOKEN_EXPIRY: 15d # Expiry time for refresh token
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
        run: |
          cd Backend
          npm run test

  deploy-to-render:
    runs-on: ubuntu-latest
    needs: [run-unit-tests]
    if: ${{ needs.run-unit-tests.result == 'success' }}
    steps:
      - name: Trigger deployment webhook
        run: curl -X POST -d '{}' ${{ secrets.RENDER_DEPLOYMENT_WEBHOOK_URL }}

  send-notification-to-discord:
    runs-on: ubuntu-latest
    needs: [deploy-to-render, run-unit-tests]
    steps:
      - name: Deployment Success
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ needs.run-unit-tests.result == 'success' }}
        with:
          severity: info
          details: Deployment Succeeded!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Deployment Failure
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ needs.run-unit-tests.result == 'failure' }}
        with:
          severity: error
          details: Deployment Failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Deployment Cancelled
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ needs.run-unit-tests.result == 'cancelled' }}
        with:
          severity: warn
          details: Deployment Cancelled!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
