name: Petopia Market

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x] # Corrected node version
        mongodb-version: ["6.0"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: test-rs
          mongodb-port: 27017

      - name: Install backend dependencies
        run: |
          cd Backend
          npm install

      - name: Run backend tests
        env:
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
          ACCESS_TOKEN_EXPIRY: 2d
          REFRESH_TOKEN_EXPIRY: 15d
        run: |
          cd Backend
          npm run test

  deploy-to-render:
    runs-on: ubuntu-latest
    needs: [run-unit-tests]
    if: ${{ needs.run-unit-tests.result == 'success' }}
    steps:
      - name: Trigger deployment webhook
        run: curl -X POST -d '{}' ${{ secrets.RENDER_DEPLOYMENT_WEBHOOK_URL }}

  send-notification-to-discord:
    runs-on: ubuntu-latest
    needs: [run-unit-tests]
    if: ${{ always() }} # Always run this job
    steps:
      - name: Notify Discord
        if: ${{ needs.run-unit-tests.result != null }} # Check if any tests were run
        uses: rjstone/discord-webhook-notify@v1
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: ${{ needs.run-unit-tests.result == 'success' ? 'info' : 'error' }} # Set severity based on test result
          details: |
            ${{ if(needs.run-unit-tests.result == 'success', 'New Deployment Successfully Done!', 'Deployment Failed!') }}
